### ISSUE TITLE
Fix mobile banner

### ISSUE THREAD

**Issue by ocni-dtu** [riselabs-at/gbdi#9]
The title on the banner section of the pager is too big, when viewed on mobile. See below.

![Screenshot_2024-03-04-17-38-15-74_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/riselabs-at/gbdi/assets/16247318/6377f895-5630-4e45-a342-91adbcc56ec5)

Change the font size on mobile, desktop sizes should stay the same.

**Comment by HxnDev** [comment]
- Styling is done in tailwind
- To Lookup documentations to see how to do individual styling for different devices

**Comment by HxnDev** [comment]
Added breakpoint to resolve the mobile banner issue.

Used "sm" property.
Any device whose screen width is greater than 640px (Tablets and Laptops etc) will be shown the 8xl and 4xl font size of headings and paragraph respectively (As is currently being done)
Any device whose screen width is less than 640px (Mobile phones) will be shown 4xl and 2xl font sizes for headings and paragraphs respectively.
Tested the above on localhost of mobile.
